### ISSUE TITLE
项目工程名

### ISSUE THREAD

**Issue by jhappye** [rememberber/WeSync#2]
你好，请问下这个项目没有项目文件吗？请问如何用idea跑起来，谢谢！

**Comment by rememberber** [comment]
抱歉，历史遗留问题，导致该工程跑起来较繁琐，看来我有必要抽空把它转成maven工程好好整理一下了；

您目前可以尝试以下步骤：

1. clone
2. 指定jdk
3. 在intellij idea中指定src为source目录
3.5 在lib右键，add as library
4. 处理报错的文件编码修改为gbk
5. 找到AppMainWindow类，执行main方法


祝好运，我会尽快抽时间好好重构一下

**Comment by rememberber** [comment]
已经改成maven工程了

**Comment by jhappye** [comment]
非常感谢！
