### ISSUE TITLE
效率怎么样?

### ISSUE THREAD

**Issue by wenzewoo** [rememberber/WeSync#5]
效率怎么样?

**Comment by rememberber** [comment]
感谢关注！

由于采用的是文件快照原理，只适用于百万条数据量以下的数据库，

而且目前这个项目适合做UI参考和思路参考，
因为部分逻辑由于业务相关性的原因，已经脱敏，可能会影响部分功能，

这是很久以前的一个项目，暂时没有精力继续维护了

**Comment by nmexyuluo** [comment]
您好，您的邮件已经收到，稍后回复。
